### ISSUE TITLE
Where is the data for check_szcomp.c?

### ISSUE THREAD

**Issue by schwehr** [MathisRosenhauer/libaec#11]
From `szcomp.sh`:

```
testfile=${srcdir}/../data/121B2TestData/ExtendedParameters/sar32bit.dat
```
Can you add this file to the project or can you provide an alternate?

**Comment by MathisRosenhauer** [comment]
The sample data from CCSDS is not part of the repo, only the source tarballs include them. I will add a target for CMake to download the data (autoconf already has one: `make update-sampledata`).
