### ISSUE TITLE
Request for version 1.0.5 with git tag

### ISSUE THREAD

**Issue by jwsblokland** [MathisRosenhauer/libaec#18]
Hello Mathis,

The libaec pull request (https://github.com/HDFGroup/hdf5/pull/703) for HDF5 is almost accepted. If you read the pull request they are eager to make use of version 1.0.5 because it has more straightforward HDF5 integration. Would it be possible to make an official 1.0.5 release with a proper git tag?

Best regards,
   Jan-Willem

**Comment by MathisRosenhauer** [comment]
Hi Jan-Willem,

I just tagged version 1.0.5.

Cheers,
Mathis

**Comment by jwsblokland** [comment]
Thanks!

**Comment by jwsblokland** [comment]
Just for your information. The libaec pull request for HDF5 has been approved.
