### ISSUE TITLE
Can't submit MRs to the gitlab repo!

### ISSUE THREAD

**Issue by paulharris** [MathisRosenhauer/libaec#22]
Hi,

Your gitlab repo requires LDAP login, which means noone can submit issues or PRs/MRs to your project!

There are some patches in the conan recipe that you might like to fold in.

cheers,
Paul

**Comment by MathisRosenhauer** [comment]
Hi Paul,

You can submit your PR here. I sync the repos both ways.

Cheers,
Mathis

**Comment by paulharris** [comment]
Hi Mathis,

Ok cool. You should probably mention that here, because it looks like the official repo is the other one, and in other projects that have an official repo elsewhere, they often ignore the github repo.

I don't use libaec directly, I'm just updating a "recipe" for conan that builds libaec.
There are various patches to allow libaec to build nicely on multiple platforms.

I had to add a line to CMakeLists.txt:
```
--- a/CMakeLists.txt	2021-09-17 19:28:01.000000000 +0800
+++ b/CMakeLists.txt	2022-11-04 07:43:58.413439439 +0800
@@ -12,6 +12,8 @@
 include(TestBigEndian)
 test_big_endian(WORDS_BIGENDIAN)
 
+set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
+
 # Check for __builtin_clzll for faster decoding
 include(CheckCSourceCompiles)
 check_c_source_compiles(
```

Without this, Ninja complains of two "aec" targets going to the same output directory.

There are other patches, perhaps you are interested in taking some of the ideas and folding them into your upstream project?  I thought I'd point it out and let you decide.

This is the location of libaec's recipe and patches:
https://github.com/conan-io/conan-center-index/tree/master/recipes/libaec/all

Best regards,
Paul

**Comment by MathisRosenhauer** [comment]
Thanks for the patch but this creates problem with testing and benchmarking scripts. While those could be adapted, they would then stop working in the legacy autoconf build system. I will try to find another way to make ninja happy.

**Comment by paulharris** [comment]
Ok, good luck,
perhaps another approach is to rename the other object named 'aec',
I seem to recall there was an intermediate target called aec that could be renamed?
