### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by simonkingrwe** [MathisRosenhauer/libaec#36]
I am attempting to decode the ECMWF Open Data Grib files using a C# .net application, I have used NGrib to decode files from NOAA and ECMWF GRIB1 files. The ECMWF data is encoded using the CCSDS compression methodology and references this library in their notes ([See here](https://codes.ecmwf.int/grib/format/grib2/templates/5/42/)).  However, NGrib doesn't currently support template 42 so I am looking at how I can do that.

I have extracted a single GRIB2 file from the open data repository and when run through WGRIB produces the expected results. However, when I run the data from the data section through the libaec library I am not seeing the bitmap data I expect. I have extracted the parameters for the aec_strm from the GRIB file and then call greac.exe and pass in the raw data as a file.

I am sure I am doing something wrong so I wanted to reach out to see if you can help. The command I have used is as follows

`graec -d -3 -m -s -r 128 -j 32 -n 12 data-section.source data-section.dest`

The open source data is here [ECMWF Open Data](https://data.ecmwf.int/forecasts/), I am looking at the ensemble data, my process is to download the index file locate the sections I want for each ensemble member and then download each section individually as a binary file. Once the download completes I open it using NGrib and then look to process it extracting the raw compressed data. Once I have the raw data as a byte array and the parameters I pass that in to libaec via C# interop. 

However, as that process produced results that didn't match what I saw from WGRIB I saved the raw compressed data to a binary file and run that through the graec using the above command. Doing that I get the same results as running it through my wrapper.

Any help would be much appreciated.

**Comment by joobog** [comment]
To extract values from a GRIB2 file that uses CCSDS, more steps are required:
1. Firstly, the data is unpacked with AEC.
2. The unpacked output is then decoded using Simple Packing.
3. If necessary, missing values must be added to the appropriate places.

Here is an example (without missing values):
```
#!/bin/bash -e

infileGrib2=20240729000000-0h-oper-fc.grib2
msg1Grib2=msg1.grib2
ccsdsBin=ccsds.bin
simpelBin=simple.bin

if [ ! -f $infileGrib2 ]; then
  wget "https://data.ecmwf.int/forecasts/20240729/00z/aifs/0p25/oper/$infileGrib2"
fi

grib_copy -w count=1 $infileGrib2 $msg1Grib2

set -x
bitsPerValue=$(grib_get -p bitsPerValue $msg1Grib2)
binaryScaleFactor=$(grib_get -p binaryScaleFactor $msg1Grib2)
decimalScaleFactor=$(grib_get -p decimalScaleFactor $msg1Grib2)
referenceValue=$(grib_get -p referenceValue $msg1Grib2)
startOffset=$(grib_get -p offsetBeforeData $msg1Grib2)
endOffset=$(grib_get -p offsetAfterData $msg1Grib2)
bytesPerValue=$(($bitsPerValue/8))
bscale=$(echo "2^$binaryScaleFactor" | bc -l)
dscale=$(echo "10^$decimalScaleFactor" | bc -l)

dd if=$msg1Grib2 of=$ccsdsBin bs=1 skip=$startOffset count=$((endOffset-startOffset))
graec -d -3 -m -s -r 128 -j32 -n16 $ccsdsBin $simpelBin
set +x

for i in {0..6}; do
  simple=$(od -An -v -tu2 -w2 --endian=big -j $((i*$bytesPerValue)) -N $bytesPerValue $simpelBin)
  value=$(echo "($simple * $bscale + $referenceValue) * $dscale" | bc -l)
  echo "value[$i] = ($simple * $bscale + $referenceValue) * $dscale = $value"
done
```

**Comment by simonkingrwe** [comment]
Thank you for your reply, I had forgotten in essence this aspect

`simple=$(od -An -v -tu2 -w2 --endian=big -j $((i*$bytesPerValue)) -N $bytesPerValue $simpelBin)`

I was treating each byte as a value before calculating 

`Y * 10D= R + (X1+X2) * 2E`

So I am happy to close this issue
