### ISSUE TITLE
Is HAVE_STDINT_H worth while?

### ISSUE THREAD

**Issue by schwehr** [MathisRosenhauer/libaec#4]
I would argue that compilers that don't have stdint.h are too old to be work supporting on the master branch of libaec.  If stdint.h isn't present (or is broken), will libaec even compile?

Using `encode_accessors.h` as an example:

```c
#include "config.h"

#if HAVE_STDINT_H
#  include <stdint.h>
#endif
```
Could be come just
```c
#include <stdint.h>
```

**Comment by MathisRosenhauer** [comment]
Since C99 is now required this certainly can go.
