### ISSUE TITLE
Overly careful fuzzer

### ISSUE THREAD

**Issue by schwehr** [MathisRosenhauer/libaec#7]
I think it might be better if the fuzzer tried both directions on all input.  The point if the fuzzer is to try to break things.  Why keep compressed data from the compressor?  

I retract this.  I now see that you need those bytes for the type check.

     Also, why the minimum size check?

**Comment by MathisRosenhauer** [comment]
By both directions you mean compressing and decompressing of the same input data? That could easily be done. Or should we feed the compressed data again to the compressor?

I use the first bytes to set compression parameters. That's why I need at least two bytes.

**Comment by schwehr** [comment]
I was thinking the same data to both compressing and decompressing.
